# Generated by Django 4.1.7 on 2023-02-24 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='has_additional_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
