# Generated by Django 4.1.7 on 2023-02-24 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
