# Generated by Django 4.1.7 on 2023-02-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userlog_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='last_job_apply_date',
            field=models.DateField(null=True, verbose_name='last job apply date'),
        ),
    ]
