# Generated by Django 4.1.7 on 2023-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='currency',
            field=models.CharField(blank=True, max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='current_salary',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last name'),
        ),
    ]
