# Generated by Django 4.1.7 on 2023-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_alter_seekerprofile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='certificate_degree_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='institute_university_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='starting_date',
            field=models.DateField(null=True),
        ),
    ]
