# Generated by Django 4.1.7 on 2023-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_alter_educationdetail_certificate_degree_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetails',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='description',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='is_current_job',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='job_location_city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='job_location_country',
            field=models.CharField(max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='job_location_state',
            field=models.CharField(max_length=50, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='job_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
