# Generated by Django 4.1.7 on 2023-03-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0005_alter_experiencedetails_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
