# Generated by Django 4.1.7 on 2023-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstream',
            name='business_stream_english_name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='businessstream',
            name='business_stream_name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
