# Generated by Django 4.1.7 on 2023-02-26 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_businessstream_business_stream_english_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessstream',
            name='business_stream_english_name',
            field=models.CharField(max_length=100, null=True, verbose_name='English name'),
        ),
    ]
