# Generated by Django 4.1.7 on 2023-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='job_type_english',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
    ]
