# Generated by Django 4.1.7 on 2023-02-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobtype_job_type_english_alter_jobtype_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_location',
        ),
        migrations.AddField(
            model_name='joblocation',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobpost'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
