# Generated by Django 4.1.7 on 2023-03-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_business_stream_and_more'),
        ('job', '0004_jobconversation_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='company.company', verbose_name='Company'),
        ),
    ]
