# Generated by Django 4.1.7 on 2023-03-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobpost_company'),
        ('job', '0007_jobpost_salary'),
    ]

    operations = [
    ]
